name: briefcase
version:  0.2.2
synopsis: Utilities for assessing value of projects
description: |
  Tools for describing finances.

stability: experimental
license: BSD3
license-file: LICENSE
author: Andrew Cowie <istathar@gmail.com>
maintainer: Andrew Cowie <istathar@gmail.com>
copyright: © 2016-2020 Athae Eredh Siniath and Others
category: Text
tested-with: GHC == 8.8.4
github: aesiniath/briefcase

dependencies:
 - base >= 4.11 && < 5
 - formatting
 - hourglass
 - text
 - core-text

ghc-options: -Wall -Wwarn -fwarn-tabs

library:
  source-dirs: lib
  exposed-modules:
  - Briefcase.CashFlow
  - Briefcase.Money
  - Briefcase.TimeValue
  - Briefcase.Utilities

tests:
  check:
    dependencies:
     - hspec
     - briefcase
    ghc-options: -threaded
    source-dirs:
     - tests
    main: CheckProgram.hs
    other-modules: []
